#!/bin/bash
if [ -z "$1" ]; then 
  echo "Usage: $0 VMNAME"
else
  ../vmxor-make $1 \
    --os fedora \
    --gb 12 \
    --dvd0 ~/.vmxor-dvds/Fedora-19-i386-DVD.iso
  echo At DVD start menu, hit ESC
  echo In boot prompt type \`linux ks=hd:fd0:/ks.cfg\`
fi
