#!/bin/bash
if [ -z "$1" ]; then 
  echo "Usage: $0 VMNAME"
else
  ../vmxor-make $1 \
    --os opensuse \
    --flop fancy \
    --gb 10 \
    --dvd0 ~/.vmxor-dvds/openSUSE-13.1-DVD-i586.iso \
    --vmxin sharedfolder.vmx.template
fi
