#!/bin/bash
if [ -z "$1" ]; then 
  echo "Usage: $0 VMNAME"
else
  ../vmxor-make $1 \
    --vmxin ../default.vmx.template \
    --os centos-64 \
    --gb 10 \
    --dvd0 ~/.vmxor-dvds/CentOS-7-x86_64-DVD-1511.iso
  echo At DVD start menu, hit ESC
  echo In boot prompt type \"linux ks=hd:fd0\"
fi
